### PR TITLE
add patron table

### PR DESCRIPTION
**Pull request by stupidsing**

### CODE REVIEW

**Comment by yookoala** [comment]
I think in modern libraries, we should have a email field in patron table. Email would be used both in login and, potentially, book renewal notification.

**Comment by tonyhhyip** [comment]
@stupidsing All the contact data should be nullable and default because sometime they store in the school office or something like that. Also, please add field which branch and birthday(nullable) is the parton, so that age limit and branch loan limit can be set.
You may refers to here http://schema.koha-community.org/tables/borrowers.html

**Comment by stupidsing** [comment]
Actually since contacts are text field, staff can already enter blank data (empty strings). Allowing nulls may cause NPE or other confusions.

I made the table with just few columns to avoid over-designing.  May easily add new columns when the case arise later on.

**Comment by tonyhhyip** [comment]
At least please add the branch and birthday field, thanks

**Comment by yookoala** [comment]
Birthday I understand, But what does "branch" means in the patrons table?

**Comment by tonyhhyip** [comment]
@yookoala Branch means which is the home branch library of the parton, some library restrict in parton check out books in non-home branch library

**Comment by stupidsing** [comment]
added.

phone and email are set to nullable since they may be used to determine if certain actions can be done, i.e. if ($phone != null) sendSms($phone)

if there is age loan limit, birthday would be a mandate field; this probably need to be verified by back-end logic.

**Pull request merged**
