### PR TITLE
Information correction in composer.json and README.md

### PR DESCRIPTION
**Pull request by yookoala**
Provide correct URL, license information in composer.json and README.md

### CODE REVIEW

**Comment by yookoala** [comment]
Why the url has to be "https://github.com/michaelachrisco/mailthief"? Any idea?

**Comment by tonyhhyip** [comment]
@yookoala Because mailthief doesn't support laravel 5.1 when I added it and I pick a fork version of it

**Comment by yookoala** [comment]
It seems if I change the repository.url, I get these errors:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1

    - The requested package tightenco/mailthief dev-dev-laravel-5.1 exists as tightenco/mailthief[dev-53-compat, dev-bl-fix-arr-first, dev-master, v0.1.0, v0.1.1, v0.2.0, v0.2.1] but these are rejected by your constraint.
```

Quite annoying.

**Comment by yookoala** [comment]
So. The problem was I understand composer.json wrong. My mistake.

**Comment by tonyhhyip** [comment]
@yookoala Please merge the new commit, I fix it

**Pull request merged**
